export const LOGIN_RESOLVED = 'LOGIN_RESOLVED'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'
export const LOGIN_PENDING = 'LOGIN_PENDING'

export const SIGNUP_RESOLVED = 'SIGNUP_RESOLVED'
export const SIGNUP_REJECTED = 'SIGNUP_REJECTED'
export const SIGNUP_PENDING = 'SIGNUP_PENDING'

export const LOGOUT_RESOLVED = 'LOGOUT_RESOLVED'
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED'
export const LOGOUT_PENDING = 'LOGOUT_PENDING'
