export const AUTH_USER_LOGIN_RESOLVED = 'AUTH_USER_LOGIN_RESOLVED'
export const AUTH_USER_LOGIN_REJECTED = 'AUTH_USER_LOGIN_REJECTED'
export const AUTH_USER_LOGIN_PENDING = 'AUTH_USER_LOGIN_PENDING'

export const AUTH_USER_LOGOUT_RESOLVED = 'AUTH_USER_LOGOUT_RESOLVED'
export const AUTH_USER_LOGOUT_REJECTED = 'AUTH_USER_LOGOUT_REJECTED'
export const AUTH_USER_LOGOUT_PENDING = 'AUTH_USER_LOGOUT_PENDING'
