export const FETCH_CURRENT_USER_PENDING = 'FETCH_CURRENT_USER_PENDING'
export const FETCH_CURRENT_USER_RESOLVED = 'FETCH_CURRENT_USER_RESOLVED'
export const FETCH_CURRENT_USER_REJECTED = 'FETCH_CURRENT_USER_REJECTED'
