export const FETCH_OPPORTUNITIES_PENDING = 'FETCH_OPPORTUNITIES_PENDING'
export const FETCH_OPPORTUNITIES_RESOLVED = 'FETCH_OPPORTUNITIES_RESOLVED'
export const FETCH_OPPORTUNITIES_REJECTED = 'FETCH_OPPORTUNITIES_REJECTED'
